name: RISI Palm Oil Data Automation

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  run_risi_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies for Chrome and Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          # Removed pymupdf and Pillow as they are no longer used
          pip install pygsheets pandas requests selenium gspread gspread-dataframe retrying

      # Removed temporary download directory creation as direct extraction is used
      # - name: Create temporary download directory
      #   run: |
      #     mkdir -p /tmp/downloads

      - name: Create Google Service Account key file
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GCP_SA_KEY" > service_account_key.json

      - name: Run RISI Palm Oil Python script
        env:
          RISI_USERNAME: ${{ secrets.RISI_USERNAME }}
          RISI_PASSWORD: ${{ secrets.RISI_PASSWORD }}
          CHROMEDRIVER_PATH: /usr/bin/chromedriver
        run: |
          python RISI_data_download.py
